<?php
  $title = 'Add new photo';
  $this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<div class="row mt-4">
  <div class="col-6">
    <?php
      $title = $form->get('title');
      $title->setAttribute('class', 'form-control');
      $title->setAttribute('placeholder', 'Awesome picture x.x');

      $caption = $form->get('caption');
      $caption->setAttribute('class', 'form-control');
      $caption->setAttribute('placeholder', 'Short awesome description!');

      $alt = $form->get('alt');
      $alt->setAttribute('class', 'form-control');
      $alt->setAttribute('placeholder', 'awesome_picture_x_x');

      $photo = $form->get('photo');
      $photo->setAttribute('class', 'form-control');
      $photo->setAttribute('placeholder', 'Choose picture to upload');

      // This provides CSS classes for the submit button:
      $submit = $form->get('submit');
      $submit->setAttribute('class', 'btn btn-primary');

      $form->setAttribute('action', $this->url('photo-gallery', ['action' => 'add']));
      $form->prepare();

      echo $this->form()->openTag($form);
    ?>

    <div class="form-group">
        <?= $this->formLabel($title) ?>
        <?= $this->formElement($title) ?>
        <?= $this->formElementErrors()->render($title, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($caption) ?>
        <?= $this->formElement($caption) ?>
        <?= $this->formElementErrors()->render($caption, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($alt) ?>
        <?= $this->formElement($alt) ?>
        <?= $this->formElementErrors()->render($alt, ['class' => 'help-block']) ?>
    </div>
    <div class="form-group">
        <?= $this->formLabel($photo) ?>
        <?= $this->formFile($photo) ?>
        <?= $this->formElementErrors()->render($photo, ['class' => 'help-block']) ?>
    </div>

    <?php
      echo $this->formSubmit($submit);
      echo $this->formHidden($form->get('id'));
      echo $this->form()->closeTag();
    ?>
  </div>
</div>