<?php
  $title = 'Delete photo';
  $url= $this->url('photo-gallery', ['action' => 'delete', 'id' => $id]);
  $this->headTitle($title);
?>
<div class="text-center">
  <h1><?= $this->escapeHtml($title) ?></h1>

  <p>
    Are you sure that you want to delete this awesome photo?
    <figure class="figure">
      <img
        src="/upload/img/thumbnail/<?= $photo->img_name ?>" 
        class="figure-img img-fluid rounded"
        alt="<?= $this->escapeHtml($photo->alt) ?>"
      >
      <figcaption class="figure-caption"><?= $this->escapeHtml($photo->title) ?></figcaption>
    </figure>
  </p>

  <form action="<?= $url ?>" method="post">
  <div class="form-group">
      <input type="hidden" name="id" value="<?= (int) $photo->id ?>" />
      <input type="submit" class="btn btn-danger" name="del" value="Yes" />
      <input type="submit" class="btn btn-success" name="del" value="No" />
  </div>
  </form>
</div>
